In [2]:
import numpy as np
import random

array=np.arange(1,6).reshape(1,5)
print(array)
for i, r in enumerate(array.flat):
    print(f"sqwaur{i+1}, r={r} , area={round(22/7*(r**2))}")

[[1 2 3 4 5]]
sqwaur1, r=1 , area=3
sqwaur2, r=2 , area=13
sqwaur3, r=3 , area=28
sqwaur4, r=4 , area=50
sqwaur5, r=5 , area=79


In [3]:
ary=np.random.randint(1,100,[5,5])
print(ary)
ary>75

[[92  9 90 71 18]
 [52  7 21 51 65]
 [78 67 99 96 98]
 [28 44  7 67 46]
 [41 74 69 94  8]]


array([[ True, False,  True, False, False],
       [False, False, False, False, False],
       [ True, False,  True,  True,  True],
       [False, False, False, False, False],
       [False, False, False,  True, False]])